UPDATE `items` 
	SET `name` = 'small_chombo', 
	`title` = 'Small Chombo', 
	`description` = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec cursus mi. Cras eget erat mollis, tristique tellus in, congue odio. Cras bibendum, enim nec tincidunt aliquet, nisi diam placerat lectus, a viverra quam tellus id elit. Ut enim nibh, pellentesque placerat quam eget, laoreet dictum ipsum. Praesent aliquet placerat fermentum. Nulla interdum, magna nec auctor ultrices, nunc elit sodales ex, sit amet ultricies ante arcu et magna. Maecenas ac malesuada lectus. Praesent sodales pellentesque ipsum et semper. Suspendisse lacinia eleifend urna vitae bibendum. In eget pellentesque lectus, nec mattis dui. Pellentesque non felis a urna rutrum sodales quis et erat. Cras eros turpis, tincidunt quis pharetra ut, varius a nibh. Quisque aliquam mi nunc, ac pulvinar nulla blandit id. Maecenas id dui egestas, pulvinar sapien ac, luctus tortor. Duis ac dolor at urna commodo vehicula nec et felis. Aliquam a purus malesuada, suscipit turpis eu, consequat purus.', 
	`price` = '300.00', 
	`short_description` = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec cursus mi. Cras eget erat mollis, tristique tellus in, congue odio. Cras bibendum, enim nec tincidunt aliquet, nisi diam placerat lectus, a viverra quam tellus id elit. Ut enim nibh, pellentesque placerat quam eget, laoreet dictum ipsum. Praesent aliquet placerat fermentum. Nulla interdum, magna nec auctor ultrices, nunc elit sodales ex, sit amet ultricies ante arcu et magna. Maecenas ac malesuada lectus. Praesent sodales pellentesque ipsum et semper.' 
WHERE `items`.`id` = 1;

INSERT into `items` (`name`,`title`,`description`,`price`,`created`,`max_parts`,`short_description`)
values ("medium_chombo", "Medium Chombo", 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec cursus mi. Cras eget erat mollis, tristique tellus in, congue odio. Cras bibendum, enim nec tincidunt aliquet, nisi diam placerat lectus, a viverra quam tellus id elit. Ut enim nibh, pellentesque placerat quam eget, laoreet dictum ipsum. Praesent aliquet placerat fermentum. Nulla interdum, magna nec auctor ultrices, nunc elit sodales ex, sit amet ultricies ante arcu et magna. Maecenas ac malesuada lectus. Praesent sodales pellentesque ipsum et semper. Suspendisse lacinia eleifend urna vitae bibendum. In eget pellentesque lectus, nec mattis dui. Pellentesque non felis a urna rutrum sodales quis et erat. Cras eros turpis, tincidunt quis pharetra ut, varius a nibh. Quisque aliquam mi nunc, ac pulvinar nulla blandit id. Maecenas id dui egestas, pulvinar sapien ac, luctus tortor. Duis ac dolor at urna commodo vehicula nec et felis. Aliquam a purus malesuada, suscipit turpis eu, consequat purus.', '400.00', '2017-05-05 07:12:00', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec cursus mi. Cras eget erat mollis, tristique tellus in, congue odio. Cras bibendum, enim nec tincidunt aliquet, nisi diam placerat lectus, a viverra quam tellus id elit. Ut enim nibh, pellentesque placerat quam eget, laoreet dictum ipsum. Praesent aliquet placerat fermentum. Nulla interdum, magna nec auctor ultrices, nunc elit sodales ex, sit amet ultricies ante arcu et magna. Maecenas ac malesuada lectus. Praesent sodales pellentesque ipsum et semper.'),

	("large_chombo", "Large Chombo", 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec cursus mi. Cras eget erat mollis, tristique tellus in, congue odio. Cras bibendum, enim nec tincidunt aliquet, nisi diam placerat lectus, a viverra quam tellus id elit. Ut enim nibh, pellentesque placerat quam eget, laoreet dictum ipsum. Praesent aliquet placerat fermentum. Nulla interdum, magna nec auctor ultrices, nunc elit sodales ex, sit amet ultricies ante arcu et magna. Maecenas ac malesuada lectus. Praesent sodales pellentesque ipsum et semper. Suspendisse lacinia eleifend urna vitae bibendum. In eget pellentesque lectus, nec mattis dui. Pellentesque non felis a urna rutrum sodales quis et erat. Cras eros turpis, tincidunt quis pharetra ut, varius a nibh. Quisque aliquam mi nunc, ac pulvinar nulla blandit id. Maecenas id dui egestas, pulvinar sapien ac, luctus tortor. Duis ac dolor at urna commodo vehicula nec et felis. Aliquam a purus malesuada, suscipit turpis eu, consequat purus.', '500.00', '2017-05-05 07:12:00', 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec cursus mi. Cras eget erat mollis, tristique tellus in, congue odio. Cras bibendum, enim nec tincidunt aliquet, nisi diam placerat lectus, a viverra quam tellus id elit. Ut enim nibh, pellentesque placerat quam eget, laoreet dictum ipsum. Praesent aliquet placerat fermentum. Nulla interdum, magna nec auctor ultrices, nunc elit sodales ex, sit amet ultricies ante arcu et magna. Maecenas ac malesuada lectus. Praesent sodales pellentesque ipsum et semper.');
	   